### ISSUE TITLE
Plugin doesn't start

### ISSUE THREAD

**Issue by declain** [Rem0o/FanControl.HWInfo#3]
This is copied from log file:

5.4.2021. 12:01:38: System.IO.FileNotFoundException: Unable to find the specified file.
   at FanControl.HWInfo.HWInfo..ctor() in C:\projects\fancontrol-hwinfo\HwInfo.cs:line 38
   at FanControl.HWInfo.HWInfoPlugin.Initialize() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 18
   at FanControl.Domain.ComputerAccessLayer.Initialize(Nullable`1 disableStorage)

**Comment by Rem0o** [comment]
You don't have shared memory on?

**Comment by declain** [comment]
I do.

![image](https://user-images.githubusercontent.com/33282149/113601608-daa1a780-9641-11eb-9746-6b34e5373e52.png)

**Comment by Rem0o** [comment]
Can you attach a debugger and see the problem?

**Comment by declain** [comment]
I don't know how to do that, I'm not a programmer, just a regular user.

**Comment by Rem0o** [comment]
Is HWInfo running (sensors) before FanControl starts?

**Comment by declain** [comment]
Thank you! I started HWInfo in sensors only mode nd it works now!
