### ISSUE TITLE
HWInfo could not initialize or has no sensors

### ISSUE THREAD

**Issue by XYZliang** [Rem0o/FanControl.HWInfo#34]
I installed a adjustable fan on the memory of the chassis. I want to control the fan by monitoring the temperature of the memory, but the FanControl does not have the temperature of the memory I need, so I try to use your plug-in.
I downloaded the latest version of FanControl(V142), FanControl.hwinfo (1.2), HWiNFO64(7.34-4930),
After following the steps, FanControl can recognize the HWInfo plug-in and I have enabled it. At the same time I started HWiNFO in sensor-only mode and checked the "Enable reporting to Gadget" check box while selecting "Report Values in Gadget" for the memory temperature sensor.
But nothing seems to have changed in FanControl. When I tried "Refesh sensors detection", FanControl showed "HWInfo could not initialize or has no sensors".
![image](https://user-images.githubusercontent.com/59312540/211735425-e9c77585-32c0-46cc-a0f4-0421348fe4fd.png)

**Comment by Rem0o** [comment]
Any logs.txt? 

Also, take a look at your windows registry, this location:
Computer\HKEY_CURRENT_USER\Software\HWiNFO64\VSB

There should be an entry in there per sensor you export for HWInfo.

**Comment by XYZliang** [comment]
我在关闭了其他插件仅开启HWInfo并删除旧的log文件后，尝试刷新传感器数据甚至是重启FanControl，在出现无法初始化的错误后，我发现FanControl并没有输出任何log文件内容。
注册表目录内包含了我所需要的条目：
![image](https://user-images.githubusercontent.com/59312540/213459739-60afd5a5-abcb-4f28-88cf-14e6d8eb1d41.png)

**Comment by Rem0o** [comment]
I suspect the "non ascii" entries ( is that chinese ? ) causing problem.

**Comment by XYZliang** [comment]
> 我怀疑“非ascii”条目（是中文吗？）引起了问题。

Thank you for your reply, as you guessed, it is in Chinese. I changed the name of the entry, but the problem persists.
![image](https://user-images.githubusercontent.com/59312540/213774750-e8d4e4d7-2ae9-470a-b51e-3cda81c03f05.png)

**Comment by Rem0o** [comment]
Any Logs.txt in fancontrol's folder?

**Comment by virtuoso-00** [comment]
Had the same issue. Easy fix after looking at the log:

![image](https://user-images.githubusercontent.com/61610006/216794775-ff9e0625-6be8-4779-ac04-51b8e4065482.png)

**Comment by MiyukiLoveu** [comment]
same issue
![1](https://user-images.githubusercontent.com/28448349/220367789-ac1cd58a-3da1-487f-9283-7e0d4aaa723e.PNG)
![2](https://user-images.githubusercontent.com/28448349/220367797-6acf9332-2ef5-46b8-8e52-7f56936cbd81.PNG)
![3](https://user-images.githubusercontent.com/28448349/220367986-3839b302-1ccb-45ef-84f5-4363504e2e84.PNG)

**Comment by Rem0o** [comment]
@MiyukiLoveu  make sure HWInfo is open in sensor mode, with some sensors exported to gadget.

**Comment by chaoyue1024** [comment]
> 

你好，你最后解决了不能识别内存温度的bug了吗，我碰到了一样的情况。日志里面没看懂，就一行HWInfo could not initialize or has no sensors.

**Comment by chaoyue1024** [comment]
Had the same issue.
<img width="1016" alt="屏幕截图 2023-02-24 053834" src="https://user-images.githubusercontent.com/126206583/221042380-02d464a5-a7c0-4786-879a-45d27ba5ca60.png">

**Comment by MiyukiLoveu** [comment]
> @MiyukiLoveu make sure HWInfo is open in sensor mode, with some sensors exported to gadget.

Thank you , it works

**Comment by juzi5201314** [comment]
same issue. already exported the sensors to the gadget. The log only shows `HWInfo could not initialize or has no sensors.`

**Comment by XYZliang** [comment]
> same issue

same issue and same log

**Comment by mumyeong54** [comment]
Adding power[W] gives the same error.
HWInfo -> Configure Sensors -> Customize, solved in changed units.

**Comment by MojoMC** [comment]
Same problem here.

Log entry: "HWInfo could not initialize or has no sensors."
HWInfo is running in sensor mode, reporting to gadget is enabled and individual sensors are ticked off to report the values to gadget.
The entries in the registry at HKEY_CURRENT_USER\Software\HWiNFO64\VSB are there, without non-ASCII characters.
Latest version of FanControl (V153), latest version of FanControl.HWInfo (V1.3). Plugins-Folder created in FanControl and FanControl.HWInfo.dll copied there. The dll is not blocked/locked.
FanControl is started from the folder, not from a desktop shortcut.

Any ideas?
I need HWInfo because LibreHardwareMonitor isn't finding any sensors at all.

**Comment by pheare** [comment]
I am seeing this issue as well for every sensor I try other than CPU (Tctl/Tdie).

In hWiNFO Gadget tab if I have CPU (Tctl/Tdie) selected (Report value in Gadget), I do not get the "HWInfo could not initialize or has no sensors." error, but none of the other sensors I've selected (GPU Core Load, for example) are selectable in Fan Control.

If I remove CPU (Tctl/Tdie) in hWiNFO Gadget then I get the error - even though I still have other sensors selected.

**Comment by MojoMC** [comment]
> In hWiNFO Gadget tab if I have CPU (Tctl/Tdie) selected (Report value in Gadget), I do not get the "HWInfo could not initialize or has no sensors." error, but none of the other sensors I've selected (GPU Core Load, for example) are selectable in Fan Control.

I would try this but my platform does not offer those sensors in HWInfo.


@Rem0o Any updates on this issue or suggestions how we can assist to further troubleshoot this problem?

**Comment by Milkiananas** [comment]
Some comments: the unit for the sensor readings has to be °C, and if not, can be renamed it in HWiNFO.

**Comment by Fooughhy** [comment]
Have we always had to enable "Report value in Gadget"? I thought I had used this plugin before, but I have never enabled any values in the "HWiNFO Gadget" tab at all.

I did that now, and got this error when I refresh sensors in Fan.Control:

> 2023-05-20 06:46:30: Unhandled exception in FanControl v157.0.0.0
2023-05-20 06:46:30: System.Exception: HWInfo sensors failed: HWInfo/GPU [#0]: NVIDIA GeForce RTX 3070: /GPU Hot Spot Temperature/°C
   vid FanControl.HWInfo.HWInfoPlugin.Update() i C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:rad 93
   vid FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   vid System.Collections.Generic.List`1.ForEach(Action`1 action)
   vid FanControl.Domain.ComputerAccessLayer.Update()
   vid FanControl.Domain.ApplicationClock.DoActions()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   vid System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Also, the first response from @Rem0o :

> Any logs.txt?
> 
> Also, take a look at your windows registry, this location: Computer\HKEY_CURRENT_USER\Software\HWiNFO64\VSB
> 
> There should be an entry in there per sensor you export for HWInfo.

I do not have a "folder" called "VSB" there. I only have "Sensors" and "Summary". Is that incorrect?

**Comment by abcdehc** [comment]
i have vsb and value, my problem is same with @XYZliang 
i guess its becaues the some formatting is incorrect, maybe a separator, maybe a unit of measurement.
![1](https://github.com/Rem0o/FanControl.HWInfo/assets/44539520/08f6b22e-dac8-4870-97f8-3d7dd8f18b30)
![2](https://github.com/Rem0o/FanControl.HWInfo/assets/44539520/206ab66d-b714-409d-bdc6-ea4322f2e89f)
![3](https://github.com/Rem0o/FanControl.HWInfo/assets/44539520/c4f08dee-6563-4948-b935-e61bf4b44709)
![4](https://github.com/Rem0o/FanControl.HWInfo/assets/44539520/05096786-6ee4-44e9-904a-5d119db902f2)

**Comment by XYZliang** [comment]
@Rem0o I recently reinstalled my system and tried to re-use the plugin.
The problem is the same as before, but this time the logs have some information about the error reported as:
"2023/7/8 22:53:31: System.Exception: HWInfo is not running or reporting to gadget is not enabled.
   At FanControl.HWInfo.HWInfoPlugin.Initialize() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 27
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()"
But I'm sure hwinfo is running and has two temperatures open. I can see the corresponding entries in the registry HKEY_CURRENT_USER\Software\HWiNFO64\VSB

**Comment by XYZliang** [comment]
> 我有 VSB 和值，我的问题与我想它的原因相同，因为某些格式不正确，也许是分隔符，也许是度量单位。 ![1](https://user-images.githubusercontent.com/44539520/250134729-08f6b22e-dac8-4870-97f8-3d7dd8f18b30.png) ![2](https://user-images.githubusercontent.com/44539520/250134769-206ab66d-b714-409d-bdc6-ea4322f2e89f.png) ![3](https://user-images.githubusercontent.com/44539520/250134808-c4f08dee-6563-4948-b935-e61bf4b44709.png) ![4](https://user-images.githubusercontent.com/44539520/250134834-05096786-6ee4-44e9-904a-5d119db902f2.png)

你的日志文件有内容吗？我之前使用aida64插件替代，但aida内存显示经常不稳定，还是hwinfo的检测靠谱，可是这个插件还是没法用，日志现在的报错说我没开报告功能

**Comment by XYZliang** [comment]
After several flushes, you get the following log file:

2023/7/8 22:53:31: System.Exception: HWInfo is not running or reporting to gadget is not enabled.
   at FanControl.HWInfo.HWInfoPlugin.Initialize() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 27
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
2023/7/8 23:06:24: Unhandled exception in FanControl v161.0.0.0
2023/7/8 23:06:24: System.Exception: HWInfo was closed during operation.
   at FanControl.HWInfo.HWInfoPlugin.Update() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 107
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location ---
   at FanControl.Domain.ApplicationClock.<>c__DisplayClass10_0.<DoActions>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2023/7/8 23:06:39: System.Exception: HWInfo is not running or reporting to gadget is not enabled.
   at FanControl.HWInfo.HWInfoPlugin.Initialize() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 27
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()

**Comment by ouyangyiluo** [comment]
Try this version https://github.com/Rem0o/FanControl.HWInfo/commit/c166d1467555ae702e0b979143c711835ef6643e

**Comment by haze1986** [comment]
Hi, issue persist in v1.4, having the readings in registry but fan control aren't importing them. Trying to read RPM reading of a fan that is not readable in fan control
