### ISSUE TITLE
Memory Junction Temperature Sensor stops reporting to FanControl 

### ISSUE THREAD

**Issue by DKogut17** [Rem0o/FanControl.HWInfo#55]
Using a 3090 and getting this error in the FanControl logs after a fresh install of this plugin. It works for about 3 minutes and then this:

`3/12/2024 12:09:00 PM: System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
3/12/2024 12:11:14 PM: HWInfo sensor failed momentarily during operation: HWInfo/GPU [#0]: NVIDIA GeForce RTX 3090: /GPU Temperature/°C - Missing
HWInfo/GPU [#0]: NVIDIA GeForce RTX 3090: /GPU Memory Junction Temperature/°C - Missing
3/12/2024 12:11:14 PM: Unhandled exception in FanControl v181.0.0.0
3/12/2024 12:11:14 PM: System.Exception: HWInfo sensors failed: HWInfo/GPU [#0]: NVIDIA GeForce RTX 3090: /GPU Temperature/°C, HWInfo/GPU [#0]: NVIDIA GeForce RTX 3090: /GPU Memory Junction Temperature/°C
   at FanControl.HWInfo.HWInfoPlugin.Update()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
3/12/2024 12:12:02 PM: HWInfo sensor failed momentarily during operation: HWInfo/GPU [#0]: NVIDIA GeForce RTX 3090: /GPU Temperature (HW)/°C - Missing
3/12/2024 12:12:18 PM: HWInfo sensor failed momentarily during operation: HWInfo/GPU [#0]: NVIDIA GeForce RTX 3090: /GPU Temperature (HW)/°C - Missing
3/12/2024 12:12:18 PM: Unhandled exception in FanControl v181.0.0.0
3/12/2024 12:12:18 PM: System.Exception: HWInfo sensors failed: HWInfo/GPU [#0]: NVIDIA GeForce RTX 3090: /GPU Temperature (HW)/°C
   at FanControl.HWInfo.HWInfoPlugin.Update()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by DKogut17** [comment]
I want to leave this up but the issue has not occurred since I've ended the Rainmeter process. It could be that there was a conflict with that because I had it graph the temperature on my desktop as well.
