### ISSUE TITLE
Make Plugin more robust against HWiNFO64 restarts

### ISSUE THREAD

**Issue by hgross** [Rem0o/FanControl.HWInfo#65]
FanControl.HWInfo usually starts up successfully and is able to read my HWiNFO64 exports but whenever I have to restart HWiNFO the Plugin just stops by [throwing an exception](https://github.com/Rem0o/FanControl.HWInfo/blob/11d267b237a82edb752e604a9d83df2c5f468de6/HWInfoPlugin.cs#L83) and never recovers:

``` txt
19.12.2024 16:15:02: Update - System.Exception: HWInfo was closed during operation.
   at FanControl.HWInfo.HWInfoPlugin.Update() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 83
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at FanControl.Domain.ComputerAccessLayer.Update()
```

Unfortunately I have to restart HWiNFO64 regularly since I use [this plugin on my Streamdeck ](https://github.com/shayne/hwinfo-streamdeck/tree/main )which regularly doesn't initialize correctly. 

Can we get a more robust "reconnect/reactivate" mechanism in those cases?

**Comment by Rullarfram** [comment]
I've set up task with a delay start at logon. It starts a powershell script. The script looks for the hwinfo process to see if it's running or not. If it isn't, it will show a notification that hwinfo isn't running and try to re-launch it automatically, followed by shutting down and re-launching fancontrol in order to refresh sensors. The script is set to loop every 1min checking if hwinfo is running or not. If it's running, nothing happens. 

Would be easier/cleaner if there was a way to just refresh sensors without having to restart it. But that requires fancontrol to be brought to the front as far as i know. 

Not the cleanest of solutions, but it works.
